# Generated by Django 5.0.1 on 2024-01-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_moments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moment',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
